application: als-apps
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: latest

handlers:
- url: /static/
  static_dir: static

- url: /lowerorhigher
  script: lowerorhigher.app

- url: /drawings
  script: drawings.app
  
- url: /trees
  script: drawings.app

- url: /asciichan
  script: asciichan.app

- url: /blog
  script: blog.app

- url: /blog.*
  script: blog.app
  
- url: /wiki
  script: wiki.app
  
- url: /wiki.*
  script: wiki.app

- url: /.*
  script: als-apps.app