application: als-apps
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: latest

handlers:
- url: /stylesheets/
  static_dir: stylesheets

- url: /javascript/
  static_dir: javascript

- url: /lowerorhigher
  script: lowerorhigher.app

- url: /drawings
  script: drawings.app

- url: /asciichan
  script: asciichan.app

- url: /blog
  script: blog.app

- url: /blog.*
  script: blog.app

- url: /.*
  script: als-apps.app